tasks screen
Anna-K-S/todoey pull request #1
Opened 2023-09-20 15:30 UTC by Anna-K-S

Создан экран TasksScreen.  Добавлена FloatingActionButton для добавления новых задач. Список задач в виде ListView.builder. У каждой задачи есть свой CheckboxListTile для отметки о  выполнении задачи. Для добавления задач создан виджет AddTask, в котором есть AlertDialog для ввода текста задачи. ElevatedButton.icon позволяет добавить задачу. 

https://github.com/Anna-K-S/todoey/assets/119135816/f9c0906c-5ec3-4104-847e-336da1878604

2023-09-21 06:32 UTC, feduke-nukem requested changes

2023-09-21 06:32 UTC, feduke-nukem commented on lib/screens/tasks_screen.dart
> +        },
tear-off

2023-09-21 06:32 UTC, feduke-nukem commented on lib/screens/tasks_screen.dart
> +  final List<bool> taskCompleted = [];
Здесь лучше ввести модель типа:

```dart
class TodoTask {
  final String  title;
  final bool isCompleted;
}
```

Это было бы лучше всего, или можно воспользоваться `Map`:

```dart
final tasks = <String, bool>{};
```

Это будет лучше чем иметь два списка и обращаться по одному индексу к двум

2023-09-21 06:32 UTC, feduke-nukem commented on lib/service/add_task.dart
> +class AddTask extends StatefulWidget {
`AddTaskDialog`

2023-09-21 06:32 UTC, feduke-nukem commented on lib/service/add_task.dart
> +  final TextEditingController _taskController = TextEditingController();
Мы должны всегда освобождать ресурсы у таких вещей в `dispose` методе у стейта виджета

```dart
@override
void dispose() {
   _taskController.dispose();
   super.dispose();
}
```

2023-09-21 06:32 UTC, feduke-nukem commented on lib/service/add_task.dart
> +          },
Вынести в метод

2023-09-21 06:32 UTC, feduke-nukem commented on lib/screens/tasks_screen.dart
> +                    onChanged: (bool? newValue) {
Лучше на верочку добавить проверку, так как это `bool?`:

```dart
if(newValue == null) return;
```

2023-09-22 13:42 UTC, blagodyr-anna commented on lib/screens/tasks_screen.dart
> +                    onChanged: (bool? newValue) {
done

2023-09-22 13:42 UTC, blagodyr-anna commented on lib/service/add_task.dart
> +          },
done

2023-09-22 13:42 UTC, blagodyr-anna commented on lib/service/add_task.dart
> +  final TextEditingController _taskController = TextEditingController();
done

2023-09-22 13:42 UTC, blagodyr-anna commented on lib/service/add_task.dart
> +class AddTask extends StatefulWidget {
done

2023-09-22 13:42 UTC, blagodyr-anna commented on lib/screens/tasks_screen.dart
> +  final List<bool> taskCompleted = [];
done

2023-09-22 13:42 UTC, blagodyr-anna commented on lib/screens/tasks_screen.dart
> +        },
done

2023-09-24 08:23 UTC, feduke-nukem requested changes

2023-09-24 08:23 UTC, feduke-nukem commented on lib/screens/tasks_screen.dart
> +                        if(newValue == null) return;
Это должно быть раньше всего вообще

2023-09-25 12:06 UTC, blagodyr-anna commented on lib/screens/tasks_screen.dart
> +                        if(newValue == null) return;
done

2023-09-25 12:50 UTC, feduke-nukem approved these changes

2025-07-20 12:19 UTC, merged