New screens for the Todoey app.
Anna-K-S/todoey pull request #2
Opened 2023-09-26 15:14 UTC by Anna-K-S

* Использован пакет flutter_native_splash для изменения заставки во время загрузки приложения. 
* Созданы два новых экрана WelcomeScreen и RegistrationScreen. Для анимации логотипа прилодения использован виджет Hero. 
* В WelcomeScreen создана анимация экрана с помощью AnimatedBuilder. 
* Так же для анимации изменения цвета экрана используем ColorTween. В этом же экране появились поля для авторизации в приложении. 
* Под полями для ввода данных появились кнопки RoundedButton 'Log in' и TextButtom 'Registration'.
* На RegistrationScreen так же появились два поля для ввода email и password для регистрации в приложении.

https://github.com/Anna-K-S/todoey/assets/119135816/27494aed-f1d6-4c44-ae66-fd1c3897285f

2023-09-27 08:43 UTC, feduke-nukem requested changes

2023-09-27 08:43 UTC, feduke-nukem commented on lib/screens/welcome_screen.dart
> +    });
Не стоит так делать. Для этого есть `AnimationBuilder`.

Виджеты, которые должны обновляться относительно анимации нужно завернуть в него.

2023-09-27 08:43 UTC, feduke-nukem commented on lib/screens/welcome_screen.dart
> +  String? password;
В этих полях нет смысла, так как значения из `TextField` и так будут доступны из контроллеров: `_emailController.text`

2023-09-27 08:43 UTC, feduke-nukem commented on lib/screens/welcome_screen.dart
> +      '/registration',
Думаю, что стоит вынести эти пути роутов в одно место. Например в static поле внутри экрана, которому оно принадлежит.

2023-09-27 08:43 UTC, feduke-nukem commented on lib/screens/welcome_screen.dart
> +      arguments: '/tasks',
Зачем мы тут передаем это в качестве аргумента?

2023-09-27 08:43 UTC, feduke-nukem commented on lib/widgets/animated_welcome_screen.dart
> +class AnimatedWelcomeScreen extends StatelessWidget {
Выглядит как то что можно переделать на `AnimatedWidget` и заодно познакомиться с этим

2023-09-27 08:43 UTC, feduke-nukem commented on lib/widgets/rounded_button.dart
> +  final Function() onPressed;
`VoidCallback` вместо `Function()`

2023-09-27 08:43 UTC, feduke-nukem commented on lib/widgets/rounded_button.dart
> +          onPressed: () => onPressed(),
tear-off

2023-09-29 13:25 UTC, blagodyr-anna commented on lib/screens/welcome_screen.dart
> +    });
done

2023-09-29 13:25 UTC, blagodyr-anna commented on lib/screens/welcome_screen.dart
> +  String? password;
done

2023-09-29 13:25 UTC, blagodyr-anna commented on lib/screens/welcome_screen.dart
> +      '/registration',
done

2023-09-29 13:25 UTC, blagodyr-anna commented on lib/screens/welcome_screen.dart
> +      arguments: '/tasks',
done

2023-09-29 13:25 UTC, blagodyr-anna commented on lib/widgets/animated_welcome_screen.dart
> +class AnimatedWelcomeScreen extends StatelessWidget {
done

2023-09-29 13:25 UTC, blagodyr-anna commented on lib/widgets/rounded_button.dart
> +  final Function() onPressed;
done

2023-09-29 13:25 UTC, blagodyr-anna commented on lib/widgets/rounded_button.dart
> +          onPressed: () => onPressed(),
done

2025-07-20 12:22 UTC, merged